In [1]:
import tensorflow as tf
import numpy as np
import keras
import pandas as pd

# Load the original data
data_ori = pd.read_csv('tmdb_5000_movies.csv')
# show data detail
data_ori.head(3)

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466

In [2]:
# show columns dtypes
data_ori.dtypes

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

# transfor json object to string

In [3]:
movies = data_ori
import json
import warnings
warnings.filterwarnings('ignore')


# changing the genres column from json to string
movies['genres']=movies['genres'].apply(json.loads)
for index,i in zip(movies.index,movies['genres']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))# the key 'name' contains the name of the genre
    movies.loc[index,'genres']=str(list1)
    
# changing the keywords column from json to string
movies['keywords']=movies['keywords'].apply(json.loads)
for index,i in zip(movies.index,movies['keywords']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'keywords']=str(list1)
    
## changing the production_companies column from json to string
movies['production_companies']=movies['production_companies'].apply(json.loads)
for index,i in zip(movies.index,movies['production_companies']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'production_companies']=str(list1)
    
# changing the production_countries column from json to string    
movies['production_countries']=movies['production_countries'].apply(json.loads)
for index,i in zip(movies.index,movies['production_countries']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'production_countries']=str(list1)
    
# changing the spoken_languages column from json to string    
movies['spoken_languages']=movies['spoken_languages'].apply(json.loads)
for index,i in zip(movies.index,movies['spoken_languages']):
    list1=[]
    for j in range(len(i)):
        list1.append((i[j]['name']))
    movies.loc[index,'production_countries']=str(list1)   

data_ori.head(3)

budget                                             genres  \
0  237000000  ['Action', 'Adventure', 'Fantasy', 'Science Fi...   
1  300000000                 ['Adventure', 'Fantasy', 'Action']   
2  245000000                   ['Action', 'Adventure', 'Crime']   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   

                                            keywords original_language  \
0  ['culture clash', 'future', 'space war', 'spac...                en   
1  ['ocean', 'drug abuse', 'exotic island', 'east...                en   
2  ['spy', 'based on novel', 'secret agent', 'seq...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   

                                production_companies  \
0  ['Ingenious Film Partners', 'Twentieth Century...   
1  ['Walt Disney Pictures', 'Jerry Bruckheimer Fi...   
2             ['Columbia Pictures', 'Danjaq', 'B24']   

                                production_countries release_date     revenue  \
0                             ['English', 'Español']   2009-12-10  2787965087   
1                                        ['English']   2007-05-19   961000000   
2  ['Français', 'English', 'Español', 'Italiano',...   2015-10-26   880674609   

   runtime                                   spoken_languages    status  \
0    162.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   
1    169.0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
2    148.0  [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466

# get feaures and labels ready

In [4]:
# here are multiple methods, I go with my original way which is cumbersome but striaght forward

data_ori.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [5]:
columns = data_ori.columns
type(columns)

pandas.core.indexes.base.Index

In [6]:
columns = list(data_ori)
type(columns)

list

In [7]:
# remove colmuns that is not float
for col in columns:
    if type(col) != float:
        columns.remove(col)

columns

['genres',
 'id',
 'original_language',
 'overview',
 'production_companies',
 'release_date',
 'runtime',
 'status',
 'title',
 'vote_count']

In [8]:
# here we see some columns of type object are stil there, I don't know why. We try another method
data=data_ori.select_dtypes(exclude='object')
data.head(3)

budget      id  popularity     revenue  runtime  vote_average  \
0  237000000   19995  150.437577  2787965087    162.0           7.2   
1  300000000     285  139.082615   961000000    169.0           6.9   
2  245000000  206647  107.376788   880674609    148.0           6.3   

   vote_count  
0       11800  
1        4500  
2        4466

In [9]:
# here we choose columns that we want
features=['budget','popularity','revenue']
label=['vote_average']

In [10]:
# we change budget to float
data['budget']=data['budget']+0.0
data['revenue']=data['revenue']+0.0
data.head(1)

budget     id  popularity       revenue  runtime  vote_average  \
0  237000000.0  19995  150.437577  2.787965e+09    162.0           7.2   

   vote_count  
0       11800

In [11]:
# then we change label values according to their original value
data[label].describe()

vote_average
count   4803.000000
mean       6.092172
std        1.194612
min        0.000000
25%        5.600000
50%        6.200000
75%        6.800000
max       10.000000

In [12]:
def change(i):
    if i<=5.6:
        i=0
    if i>5.6 and i<=6.2:
        i=1
    if i>6.2 and i<=6.8:
        i=2
    if i>6.8:
        i=3
    return i
data[label]=data[label].applymap(lambda x : change(x))
data[label].head(1)        

vote_average
0             3

In [13]:
data.head(1)

budget     id  popularity       revenue  runtime  vote_average  \
0  237000000.0  19995  150.437577  2.787965e+09    162.0             3   

   vote_count  
0       11800

In [14]:
feature_data = data[features]
feature_data.head(1)


budget  popularity       revenue
0  237000000.0  150.437577  2.787965e+09

In [15]:
label_data=data[label]
label_data.head(1)

vote_average
0             3

In [16]:
# split
trainingfeatures= feature_data[:4000]
traininglabels=label_data[:4000]
testingfeatures= feature_data[4000:]
testinglabels=label_data[4000:]
dfs = [trainingfeatures,traininglabels,testingfeatures,testinglabels]

In [17]:
# write to csv files
names=['trainingfeatures','traininglabels','testingfeatures','testinglabels']
for i in range(len(dfs)):
    df = dfs[i]
    name= names[i]+'.csv'
    df.to_csv(path_or_buf=name)

In [18]:
# get datasets
x_train = pd.read_csv('trainingfeatures.csv').drop(columns=['Unnamed: 0'])
y_train = pd.read_csv('traininglabels.csv').drop(columns=['Unnamed: 0'])

temp_x=[]

for row in x_train.iterrows():
    index, data = row
    temp_x.append(data.tolist())
temp_y=[]

for row in y_train.iterrows():
    index, data = row
    temp_y.append(data.tolist())

# start neuron network

In [19]:
# Parameters
learning_rate = 0.3
num_steps = 1500
batch_size = 1000
display_step = 10

# Network Parameters
n_hidden_1 = 100 # 1st layer number of neurons
n_hidden_2 = 20 # 2nd layer number of neurons
num_input =  3 # MNIST data input (img shape: 28*28)
num_classes = 4 # MNIST total classes (0-9 digits)

# tf Graph input
X = tf.placeholder("float", [None, num_input])
Y = tf.placeholder("float", [None, num_classes])

# Store layers weight & bias
weights = {
    'h1': tf.Variable(tf.random_normal([num_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, num_classes]))
}
biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([num_classes]))
}

# Create model
def neural_net(x):
    # Hidden fully connected layer with 256 neurons
    layer_1 = tf.nn.softmax(tf.add(tf.matmul(x, weights['h1']), biases['b1']))
    # Hidden fully connected layer with 256 neurons
    layer_2 = tf.nn.relu(tf.add(tf.matmul(layer_1, weights['h2']), biases['b2']))
    # Output fully connected layer with a neuron for each class
    out_layer = tf.nn.tanh(tf.matmul(layer_2, weights['out']) + biases['out'])
    return out_layer


# Construct model
logits = neural_net(X)


# Define loss and optimizer
loss_op = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=logits, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
train_op = optimizer.minimize(loss_op)


# Evaluate model (with test logits, for dropout to be disabled)
correct_pred = tf.equal(tf.argmax(logits, 1), tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()
    
x = np.array(temp_x)

y=np.array(keras.utils.to_categorical(y_train))
dataset = tf.data.Dataset.from_tensor_slices((x,y))
iter = dataset.make_one_shot_iterator()

def next_batch(num, data, labels):
    '''
    Return a total of `num` random samples and labels. 
    '''
    idx = np.arange(0 , len(data))
    np.random.shuffle(idx)
    idx = idx[:num]
    data_shuffle = [data[ i] for i in idx]
    labels_shuffle = [labels[ i] for i in idx]

    return np.asarray(data_shuffle), np.asarray(labels_shuffle)

# Start training
with tf.Session() as sess:

    # Run the initializer
    sess.run(init)

    for step in range(1, num_steps+1):
        batch_x,batch_y=(x,y)
        # Run optimization op (backprop)
        sess.run(train_op, feed_dict={X: batch_x, Y: batch_y})
        if step % display_step == 0 or step == 1:
            # Calculate batch loss and accuracy
            loss, acc = sess.run([loss_op, accuracy], feed_dict={X: batch_x,
                                                                 Y: batch_y})
            print("Step " + str(step) + ", Minibatch Loss= " + \
                  "{:.4f}".format(loss) + ",Accuracy= " + \
                  "{:.3f}".format(acc))

    print("Optimization Finished!")

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Step 1, Minibatch Loss= 1.4028,Accuracy= 0.240
Step 10, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 20, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 30, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 40, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 50, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 60, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 70, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 80, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 90, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 100, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 110, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 120, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 130, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 140, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 150, Minibatch Loss= 1.3863,Accuracy= 0.252
Step 160, Minibatch Loss= 1.3863,Acc

In [20]:
x

array([[2.37000000e+08, 1.50437577e+02, 2.78796509e+09],
       [3.00000000e+08, 1.39082615e+02, 9.61000000e+08],
       [2.45000000e+08, 1.07376788e+02, 8.80674609e+08],
       ...,
       [2.60000000e+06, 2.27939290e+01, 1.19500000e+08],
       [2.60000000e+06, 1.40134140e+01, 3.29808800e+07],
       [2.15928000e+06, 1.32654320e+01, 1.07000000e+07]])

In [21]:
y

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [22]:
x = np.expand_dims(x,axis=0)
x

array([[[2.37000000e+08, 1.50437577e+02, 2.78796509e+09],
        [3.00000000e+08, 1.39082615e+02, 9.61000000e+08],
        [2.45000000e+08, 1.07376788e+02, 8.80674609e+08],
        ...,
        [2.60000000e+06, 2.27939290e+01, 1.19500000e+08],
        [2.60000000e+06, 1.40134140e+01, 3.29808800e+07],
        [2.15928000e+06, 1.32654320e+01, 1.07000000e+07]]])

In [23]:
y = np.expand_dims(y,axis=0)
y

array([[[0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        ...,
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]]], dtype=float32)

In [25]:
EPOCHS = 10000
BATCH_SIZE = 1000
# using two numpy arrays
features, labels = (x, y)
dataset = tf.data.Dataset.from_tensor_slices((features,labels)).repeat()
iter = dataset.make_one_shot_iterator()
x, y = iter.get_next()

# make a simple model 第一层
net = tf.layers.dense(x, 100, activation=tf.tanh) # pass the first value 

#from iter.get_next() as input 第二层
net = tf.layers.dense(net, 20, activation=tf.tanh)  # 激活函数是 tanh

prediction = tf.layers.dense(net, 4, activation=tf.tanh) #output 输出层

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=prediction, labels=y)) 

#tf.losses.mean_squared_error(prediction, y) # pass the second value 
correct_pred = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))


#from iter.get_net() as label
train_op = tf.train.AdamOptimizer().minimize(loss)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    for i in range(EPOCHS):
        _, loss_value,acc_value = sess.run([train_op, loss,accuracy])
        print("Iter: {}, Loss: {:.4f}".format(i+1, loss_value)) 
       
        print("Accurancy: " +str(acc_value))

ValueError: Failed to create a one-shot iterator for a dataset. `Dataset.make_one_shot_iterator()` does not support datasets that capture stateful objects, such as a `Variable` or `LookupTable`. In these cases, use `Dataset.make_initializable_iterator()`. (Original error: Cannot capture a stateful node (name:IteratorGetNext, type:IteratorGetNext) by value.)